### ISSUE TITLE
Java.Lang.IllegalArgumentException: itemView may not be null

### ISSUE THREAD

**Issue by mfalk118** [xamarin/Xamarin.Forms.CarouselView#28]
After upgrade of Xamarin.Android.Support.v7.RecyclerView to any newer version than 23.4.0.1 the CarouselView crashes with the below exception. Funny thing is that if i put the CarouselView inside a ListView it is working also with newer versions of Xamarin.Android.Support.v7.RecyclerView (However it is giving issues with the height of the CarouselView

Exception:
05-08 16:26:58.174 I/MonoDroid(26968): UNHANDLED EXCEPTION:
05-08 16:26:58.276 I/MonoDroid(26968): Java.Lang.IllegalArgumentException: itemView may not be null
05-08 16:26:58.276 I/MonoDroid(26968):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/4468/f913a78a/source/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
05-08 16:26:58.276 I/MonoDroid(26968):   at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x000a7] in /Users/builder/data/lanes/4468/b16fb820/source/Java.Interop/src/Java.Interop/Java.Interop/JniEnvironment.g.cs:12083 
05-08 16:26:58.280 I/MonoDroid(26968):   at Android.Runtime.JNIEnv.CallNonvirtualVoidMethod (System.IntPtr jobject, System.IntPtr jclass, System.IntPtr jmethod, Android.Runtime.JValue* parms) [0x00000] in /Users/builder/data/lanes/4468/b16fb820/source/monodroid/src/Mono.Android/JNIEnv.g.cs:444 
05-08 16:26:58.280 I/MonoDroid(26968):   at Android.Runtime.JNIEnv.InvokeConstructor (System.IntPtr instance, System.String jniCtorSignature, Android.Runtime.JValue* constructorParameters) [0x0003b] in /Users/builder/data/lanes/4468/b16fb820/source/xamarin-android/src/Mono.Android/Android.Runtime/JNIEnv.cs:469 
05-08 16:26:58.280 I/MonoDroid(26968):   at Android.Runtime.JNIEnv.FinishCreateInstance (System.IntPtr instance, System.String jniCtorSignature, Android.Runtime.JValue* constructorParameters) [0x0000b] in /Users/builder/data/lanes/4468/b16fb820/source/xamarin-android/src/Mono.Android/Android.Runtime/JNIEnv.cs:452 
05-08 16:26:58.281 I/MonoDroid(26968):   at Android.Support.V7.Widget.RecyclerView+ViewHolder..ctor (Android.Views.View itemView) [0x00071] in <cb5b48c117354edb801b7e5ff48a70e3>:0 
05-08 16:26:58.281 I/MonoDroid(26968):   at Xamarin.Forms.Platform.ItemViewAdapter+CarouselViewHolder..ctor (Xamarin.Forms.View view, Xamarin.Forms.Platform.Android.IVisualElementRenderer renderer) [0x00007] in <98ef4d3d8b214c838f1b190032afb88a>:0 
05-08 16:26:58.281 I/MonoDroid(26968):   at Xamarin.Forms.Platform.ItemViewAdapter.OnCreateViewHolder (Android.Views.ViewGroup parent, System.Int32 viewType) [0x00027] in <98ef4d3d8b214c838f1b190032afb88a>:0 
05-08 16:26:58.281 I/MonoDroid(26968):   at Android.Support.V7.Widget.RecyclerView+Adapter.n_OnCreateViewHolder_Landroid_view_ViewGroup_I (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_parent, System.Int32 viewType) [0x00011] in <cb5b48c117354edb801b7e5ff48a70e3>:0 
05-08 16:26:58.281 I/MonoDroid(26968):   at (wrapper dynamic-method) System.Object:2cc6fc7d-24f4-4367-b74e-3a2355f739f3 (intptr,intptr,intptr,int)
05-08 16:26:58.281 I/MonoDroid(26968):   --- End of managed Java.Lang.IllegalArgumentException stack trace ---
05-08 16:26:58.281 I/MonoDroid(26968): java.lang.IllegalArgumentException: itemView may not be null
05-08 16:26:58.281 I/MonoDroid(26968): 	at android.support.v7.widget.RecyclerView$ViewHolder.<init>(RecyclerView.java:9439)
05-08 16:26:58.281 I/MonoDroid(26968): 	at md56987f6cc1cad2bad7d1513f02edd2700.ItemViewAdapter_CarouselViewHolder.<init>(ItemViewAdapter_CarouselViewHolder.java:20)
05-08 16:26:58.281 I/MonoDroid(26968): 	at md56987f6cc1cad2bad7d1513f02edd2700.ItemViewAdapter.n_onCreateViewHolder(Native Method)
05-08 16:26:58.281 I/MonoDroid(26968): 	at md56987f6cc1cad2bad7d1513f02edd2700.ItemViewAdapter.onCreateViewHolder(ItemViewAdapter.java:48)
05-08 16:26:58.281 I/MonoDroid(26968): 	at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:5836)
05-08 16:26:58.281 I/MonoDroid(26968): 	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5060)
05-08 16:26:58.281 I/MonoDroid(26968): 	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4970)
05-08 16:26:58.281 I/MonoDroid(26968): 	at md56987f6cc1cad2bad7d1513f02edd2700.PhysicalLayoutManager.n_onLayoutChildren(Native Method)
05-08 16:26:58.281 I/MonoDroid(26968): 	at md56987f6cc1cad2bad7d1513f02edd2700.PhysicalLayoutManager.onLayoutChildren(PhysicalLayoutManager.java:149)
05-08 16:26:58.281 I/MonoDroid(26968): 	at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3315)
05-08 16:26:58.281 I/MonoDroid(26968): 	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3124)
05-08 16:26:58.281 I/MonoDroid(26968): 	at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3568)
05-08 16:26:58.281 I/MonoDroid(26968): 	at android.view.View.layout(View.java:18793)
05-08 16:26:58.281 I/MonoDroid(26968): 	at android.view.ViewGroup.layout(ViewGroup.java:5952)
05-08 16:26:58.281 I/MonoDroid(26968): 	at md56987f6cc1cad2bad7d1513f02edd2700.CarouselViewRenderer.n_onLayout(Native Method)
05-08 16:26:58.282 I/MonoDroid(26968): 	at md56987f6cc1cad2bad7d1513f02edd2700.CarouselViewRenderer.onLayout(CarouselViewRenderer.java:45)
05-08 16:26:58.282 I/MonoDroid(26968): 	at android.view.View.layout(View.java:18793)
05-08 16:26:58.282 I/MonoDroid(26968): 	at android.view.ViewGroup.layout(ViewGroup.java:5952)
05-08 16:26:58.282 I/MonoDroid(26968): 	at com.xamarin.forms.platform.android.FormsViewGroup.measureAndLayout(FormsViewGroup.java:28)
05-08 16:26:58.282 I/MonoDroid(26968): 	at md5b60ffeb829f638581ab2bb9b1a7f4f3f.VisualElementRenderer_1.n_onLayout(Native Method)
05-08 16:26:58.282 I/MonoDroid(26968): 	at md5b60ffeb829f638581ab2bb9b1a7f4f3f.VisualElementRenderer_1.onLayout(VisualElementRenderer_1.java:58)
05-08 16:26:58.282 I/MonoDroid(26968): 	at android.view.View.layout(View.java:18793)
05-08 16:26:58.282 I/MonoDroid(26968): 	at android.view.ViewGroup.layout(ViewGroup.java:5952)
05-08 16:26:58.282 I/MonoDroid(26968): 	at com.xamarin.forms.platform.android.FormsViewGroup.measureAndLayout(FormsViewGroup.java:28)
05-08 16:26:58.282 I/MonoDroid(26968): 	at md5b60ffeb829f638581ab2bb9b1a7f4f3f.VisualElementRenderer_1.n_onLayout(Native Method)
05-08 16:26:58.282 I/MonoDroid(26968): 	at md5b60ffeb829f638581ab2bb9b1a7f4f3f.VisualElementRenderer_1.onLayout(VisualElementRenderer_1.java:58)
05-08 16:26:58.282 I/MonoDroid(26968): 	at android.view.View.layout(View.java:18793)
05-08 16:26:58.282 I/MonoDroid(26968): 	at android.view.ViewGroup.layout(ViewGroup.java:5952)
05-08 16:26:58.282 I/MonoDroid(26968): 	at com.xamarin.forms.platform.android.FormsViewGroup.measureAndLayout(FormsViewGroup.java:28)
05-08 16:26:58.282 I/MonoDroid(26968): 	at md5b60ffeb829f638581ab2bb9b1a7f4f3f.PlatformRenderer.n_onLayout(Native Method)
05-08 16:26:58.282 I/MonoDroid(26968): 	at md5b60ffeb829f638581ab2bb9b1a7f4f3f.PlatformRenderer.onLayout(PlatformRenderer.java:63)
05-08 16:26:58.282 I/MonoDroid(26968): 	at android.view.View.layout(View.java:18793)
05-08 16:26:58.282 I/MonoDroid(26968): 	at android.view.ViewGroup.layout(ViewGroup.java:5952)
05-08 16:26:58.282 I/MonoDroid(26968): 	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
05-08 16:26:58.282 I/MonoDroid(26968): 	at android.view.View.layout(View.java:18793)
05-08 16:26:58.282 I/MonoDroid(26968): 	at android.view.ViewGroup.layout(ViewGroup.java:5952)
05-08 16:26:58.282 I/MonoDroid(26968): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
05-08 16:26:58.282 I/MonoDroid(26968): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
05-08 16:26:58.283 I/MonoDroid(26968): 	at android.view.View.layout(View.java:18793)
05-08 16:26:58.283 I/MonoDroid(26968): 	at android.view.ViewGroup.layout(ViewGroup.java:5952)
05-08 16:26:58.283 I/MonoDroid(26968): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
05-08 16:26:58.283 I/MonoDroid(26968): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
05-08 16:26:58.283 I/MonoDroid(26968): 	at android.view.View.layout(View.java:18793)
05-08 16:26:58.283 I/MonoDroid(26968): 	at android.view.ViewGroup.layout(ViewGroup.java:5952)
05-08 16:26:58.283 I/MonoDroid(26968): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
05-08 16:26:58.283 I/MonoDroid(26968): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
05-08 16:26:58.283 I/MonoDroid(26968): 	at android.view.View.layout(View.java:18793)
05-08 16:26:58.283 I/MonoDroid(26968): 	at android.view.ViewGroup.layout(ViewGroup.java:5952)
05-08 16:26:58.283 I/MonoDroid(26968): 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
05-08 16:26:58.283 I/MonoDroid(26968): 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
05-08 16:26:58.283 I/MonoDroid(26968): 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
05-08 16:26:58.283 I/MonoDroid(26968): 	at android.view.View.layout(View.java:18793)
05-08 16:26:58.283 I/MonoDroid(26968): 	at android.view.ViewGroup.layout(ViewGroup.java:5952)
05-08 16:26:58.283 I/MonoDroid(26968): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
05-08 16:26:58.283 I/MonoDroid(26968): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
05-08 16:26:58.283 I/MonoDroid(26968): 	at com.android.internal.policy.DecorView.onLayout(DecorView.java:818)
05-08 16:26:58.283 I/MonoDroid(26968): 	at android.view.View.layout(View.java:18793)
05-08 16:26:58.283 I/MonoDroid(26968): 	at android.view.ViewGroup.layout(ViewGroup.java:5952)
05-08 16:26:58.283 I/MonoDroid(26968): 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2615)
05-08 16:26:58.283 I/MonoDroid(26968): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2331)
05-08 16:26:58.283 I/MonoDroid(26968): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1490)
05-08 16:26:58.283 I/MonoDroid(26968): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7027)
05-08 16:26:58.283 I/MonoDroid(26968): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:927)
05-08 16:26:58.283 I/MonoDroid(26968): 	at android.view.Choreographer.doCallbacks(Choreographer.java:702)
05-08 16:26:58.283 I/MonoDroid(26968): 	at android.view.Choreographer.doFrame(Choreographer.java:638)
05-08 16:26:58.283 I/MonoDroid(26968): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:913)
05-08 16:26:58.283 I/MonoDroid(26968): 	at android.os.Handler.handleCallback(Handler.java:751)
05-08 16:26:58.283 I/MonoDroid(26968): 	at android.os.Handler.dispatchMessage(Handler.java:95)
05-08 16:26:58.283 I/MonoDroid(26968): 	at android.os.Looper.loop(Looper.java:154)
05-08 16:26:58.283 I/MonoDroid(26968): 	at android.app.ActivityThread.main(ActivityThread.java:6688)
05-08 16:26:58.283 I/MonoDroid(26968): 	at java.lang.reflect.Method.invoke(Native Method)
05-08 16:26:58.283 I/MonoDroid(26968): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
05-08 16:26:58.283 I/MonoDroid(26968): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)

**Comment by joaortk** [comment]
Same here... 
Will try putting it inside a listview to get it working again.

**Comment by jbravobr** [comment]
Any news about this ?

**Comment by Aumnia** [comment]
FYI, I was getting this same exception when I had forgotten to bind the ItemsSource properly in an app when converting to using Prism/Unity.

Unfortunately when I tried to make a test case to repro I can't make it fail like this.

**Comment by andi0b** [comment]
**Had the same issue, switched to the new package:** 
https://github.com/alexrainman/CarouselView
https://www.nuget.org/packages/CarouselView.FormsPlugin/
